version: '3.1'

services:
  # banco de dados relacional
  sqlserver:
    #image: mcr.microsoft.com/mssql/server
    image: mcr.microsoft.com/azure-sql-edge
    restart: always
    container_name: gama_sqlserver
    ports:
      - 1433:1433
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "yourStrong(!)Password"

